{% set name = "pytweening" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytweening-{{ version }}.tar.gz
  sha256: 8533282cf70b31de8a0499e1cf420930b0013c787118872b2ec899382792e2e6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - pip
    - python >=3.4
  run:
    - python >=3.4

test:
  imports:
    - pytweening
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/asweigart/pytweening
  summary: A collection of tweening / easing functions.
  license: BSD-3-Clause
  license_file:
    - LICENSE.txt

extra:
  recipe-maintainers:
    - jschueller
    - thewchan
