travis:
  secure:
    BINSTAR_TOKEN: Ci5qf5BljCRjqF31DnAtWba5sZrVUKrml2CpwljUULw0alcAt2+fAxfn8KD/zD/n4vaIjQXza0+I2KV3N1DcIVF5Yr82hHl8xpShsxKoYdWb6fKt7KtIabYeVtsWIBp9s7jshg/rhH6AfUO4h4gKQp4rcJEnBaRw0vDFj+5K3jCY64AeN9BrNg9A3nRIqqubZSkKulUux/oHVzeBiuhkT0/6fo0AuxlxcRsImuQ14PLpkQ3FsLqF0ms9JyymGTEgNq5YkGlBLTXuBIKhGYpiPs7fiiD+JjExPKPC5ZfaJ3pzKwYRmD+AfMSNB1rNetgkxvz4FP8MuxYD/k89Og14S4WGhw4Z2WdsUj9DIpUDYbbscvY46ZSRcapeBFL6OQpp39TGutCdWfllrGj+5cyJ1ld3U5oDFW4v6x0MGulvGLCbyAJUYeR+xcyPhZhp4BaAYhy7MVMlEb56NH2p5/8RfqMdW+mDMfC9a6ELFzB5TRYfJr5PWAfZzX7n51nYYOKo3CyfSAv6/WnzmNtTXKtiChgfOW1JalGmwQ0+dvUDwAj5n9lZbg8X8RsOurPIfrvPw59sffaekX0/AkkdP/JoA1lPeDWJj1l/Y3+7YuIF3IgBPNGC6/0S8wj5vidtccXKg+iA/GNky6pAwJS3iNpgoXmbcp9ks7q8ibB0ySzoUJA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
