travis:
  secure:
    BINSTAR_TOKEN: g+vEgeCxklrdkGG8OMYG16TQeM8TxqmImkZJ7MU1KTis7zuMNmvpiOW5PN72Ws8Li6/q5XnlImD+DzNPUJTMh1uZqVDqfdIL5aKix9Tis7x+vbyEGRRLXIu7UdORAhSCnBT4uwaYd5GLMuhCWMSexIVrDNfWKSH+XPdAmz24CP7wEfd4Wkjw+uVj2dQej8FraCz/CrkvY5qeSwcMry1BckOB70iK/RRRDBb9fw9zASFvZmPhbmJg6u6Vk39sytYNpcC8dutG8WtVOehUXV4FoXxfn/IhJsMwYOgXa6Awaw/mjlgbMXDVEBDamd3iSPUeFiXc83N4dpsNe9D0V/z1OeJZmwpI6bm6slAn7cfVrrE15pEeWR9ZqDl4ewA9gJR4CQ6/GZTNmEkA47obIN1op//SWLC/BprO+V8IVsO+7pPW6P1RvAJAS9DXtToalH01uCKTMNCE74BuX0kJtxtHIh1NjkzhBSgHH3QkcOtgHWB7ICc6sS397f93NGu3Q5X9rA5ktBXbLqpP5KBEkWy8SSJESlu1S4rBBjQ47ZwOq2V/leifXk86LgyJUiKQyo/wVOTYMgyRlwcZawxWsbBsudvGnuhf0Sdk3EmqE1TxoRRKY+ReCAeEtk0fuot+qBuQdmwF57ePmMt9c3mtpe0dl69RpjgYguKbXgkCc4DJNXE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
